services:
  nginx:
    build: ./requirements/nginx
    image: nginx
    container_name: nginx
    ports:
      - "443:443"
    restart: always
    networks:
      - inception

  mariadb:
    build: ./requirements/mariadb
    image: mariadb
    container_name: mariadb
    restart: always
    networks:
      - inception
    volumes:
      - wordpress_db:/var/lib/mysql
    secrets:
      - db_password
      - db_root_password
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}

  wordpress:
    build: ./requirements/wordpress
    image: wordpress
    container_name: wordpress
    restart: always
    networks:
      - inception

networks:
  inception:
    driver: bridge

volumes:
  wordpress_db:
    name: wordpress_db
    driver_opts:
      type: none
      o: bind
      device: /home/barmarti/data/mariadb

  wordpress_files:
    name: wordpress_files
    driver_opts:
      type: none
      o: bind
      device: /home/barmarti/data/wordpress

secrets:
  db_root_password:
    file: ../secrets/db_root_password.txt
  db_password:
    file: ../secrets/db_password.txt
