FROM debian:bookworm-20260824

RUN apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends nginx openssl \
    && rm -rf /etc/nginx/sites-enabled/default /var/lib/apt/lists/*

COPY conf/test.conf /etc/nginx/templates/test.conf
COPY html/index.html /etc/nginx/templates/test.conf

ENTRYPOINT ["nginx", "-g", "daemon off;"]
